### ISSUE TITLE
Atom parent/child validation

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#1871]
## Description

Some components can only have certain components to work. For example, `Form.Item` goes under `Form`

## Use Case

Would allow component filtering to make it easier to select valid components.

## Suggested Implementation

We've created a field called allowedChildren to add the relationship here

**Comment by ky213** [comment]
@webberwang 
in the case of an atom where all kinds of child atoms are allowed like for instance the "Body" the user will also be able to select for example "AnchorLink" atom which will throw an error immediately.
This why I suggest that we follow the approach of "atom.requiredParent" rather than "atom.allowedChildren". In this case, if the user selects an atom with a missing required parent in the builder we just show him an alert.
What do you think?

**Comment by melhamin** [comment]
@webberwang 
We already have `requiredParents` and we do validations for it as well. Why do we still need `allowedChildren` field? I belive we can achieve the desired behavior with `requiredParents` field. 

https://github.com/codelab-app/platform/assets/48331678/fa1f2cba-8a87-4aa5-9a7d-d9161556b3c1

Also, the potential issue mentioned here won't be fixed with `allowedChildren`.


> @webberwang in the case of an atom where all kinds of child atoms are allowed like for instance the "Body" the user will also be able to select for example "AnchorLink" atom which will throw an error immediately. This why I suggest that we follow the approach of "atom.requiredParent" rather than "atom.allowedChildren". In this case, if the user selects an atom with a missing required parent in the builder we just show him an alert. What do you think?

**Comment by nettohadi** [comment]
We ended up using the `requiredParents` to achieve the desired behavior. Thanks everyone for the inputs.
