### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#2041]
## What Feature Can Be Enhanced?

These are some suggestions on how to improve our UI, please give your inputs.

- [x] Move our bottom Store panel to the left panel, make it accordion style like VSCode

![Home___Builder___Codelab](https://user-images.githubusercontent.com/26264925/206671829-f1535246-2b47-4d01-865e-12f5add2ba69.jpg)

---

Openblocks put everything on the left panel, including the app state https://github.com/openblocks-dev/openblocks

![image](https://user-images.githubusercontent.com/26264925/203436345-0e6c1339-97b9-4fda-b7cb-544eb528b40d.png)

---

UIBakery also puts state there https://uibakery.io/

![_Sample__Dashboard_-_Demo___UI_Bakery](https://user-images.githubusercontent.com/26264925/206672189-9f40899a-7b2b-42cc-aae4-a1537c195723.jpg)

---

I think in general it's good to have an overview of the entire application from one place. It's like a code editor, the left panel is the explorer with a view to our entire codebase.

---

- [ ] Treat bottom panel as a modal replacement (for some data)

![Webber_Wang_s_new_App_1_and_Get_Started_and_builder-e2e_and_Cypress](https://user-images.githubusercontent.com/26264925/206673225-cb1dd129-7e78-4a2a-8554-c0e7753edff5.jpg)

A modal blocks out the rest of the page and limits interaction. We can treat the bottom panel as the modal form that creates items in the left panel.

We can create actions, state (our types) this way.

---

- [ ] Consolidate builder/page tab to a single builder/pages tab. 

Openblocks does a good job at having only 2 left sidebar items (1 is for global app state not used much). It essentially has everything in 1 view.

---

- [ ] Make the page icon a dropdown instead

**Comment by assimhabeek** [comment]
I really agree with theses enhancements.
1- Replacing modal with a bottom panel will allow quick edit to action code/properties. and believe me this is something we do a lot.
2 - One of the issues we get when putting all in the left panel is the length of element trees which require annoying scroll and same applies for state variables and actions. maybe we should use the smallest font size possible and allow one panel expanding each time.
3- Another possible suggestion for actions/state form is to put them in the right panel like we do with elements. but this way the bottom panel will have nothing or just store inspector.

**Comment by vladyslav-polishchuk** [comment]
Great ideas! A couple of tiny comments/suggestions.
- All of the above makes sense to me, but I think it may be better to not implement all the enhancements in one batch but split them into separate issues and implement them sequentially. So that there is a gap between them to collect suggestions from the entire team and adjust the plan if necessary.
- Combining pages and builder in one tab looks the most important to me, since I mostly worked on prototypes with a couple of pages and such an improvement will greatly increase my UX. One thing to consider is maybe changing how the page dropdown looks. It is been a week before I found that it was not a toggle button like all other buttons in the toolbar, but a dropdown.
<img width="396" alt="Screenshot 2022-12-09 at 23 01 50" src="https://user-images.githubusercontent.com/74900868/206796112-cc12e591-eaa6-463f-af6e-bea703a2196d.png">

 If replace it with a regular labeled select this may solve two problems at once: it will clearly indicate that there is a quick ability to change the page from there, and also there is no label that indicates on which page you are currently on (I mean name). This may look similar to this, but maybe a bit more pretty, with icon, etc
 
<img width="173" alt="Screenshot 2022-12-09 at 23 10 41" src="https://user-images.githubusercontent.com/74900868/206796702-e5454211-dc6c-4e2d-89a5-698d32eb6a79.png">
- as of suggestion moving everything into the left panel - I agree with the comment from @assimhabeek. As an alternative to the proposed solution to use small fonts and allow only one panel at a time - we may implement a similar UI that VS plugins do. I like the experience that for example GitLenght provides when you have more flexibility on large screens and can expand several sections and setup their size as needed
<img width="437" alt="Screenshot 2022-12-09 at 23 12 40" src="https://user-images.githubusercontent.com/74900868/206797246-cfa37026-0951-4fec-b819-b004423a7a51.png">

**Comment by webberwang** [comment]
> I really agree with theses enhancements. here is some of my thoughts.
> 
> 1. Replacing modal with a bottom panel will allow quick edit to action code/properties. and believe me this is something we do a lot.
> 2. One of the issues we get when putting all in the left panel is the length of element trees which require annoying scroll and same applies for state variables and actions. maybe we should use the smallest font size possible and allow one panel expanding each time.
> 3. Another possible suggestion for actions/state form is to put them in the right panel like we do with elements. but this way the bottom panel will have nothing or just store inspector.

For 2. I think we could have a dropdown filter that show/hide corresponding sections

https://user-images.githubusercontent.com/26264925/206808937-d060c80c-5c53-496c-a3d3-d8262fecd1e4.mov

**Comment by webberwang** [comment]
I agree for 2. we should have a way to show/hide appropriate data. 

- Originally I thought of a dropdown that shows the selected pane (but this only allows 1 at a time)
- Then I thought of a checkbox filter that allows any number
- The accordion solution looks most natural though

**Comment by mohasarc** [comment]
I believe all suggestions are very reasonable. I think making the UI similar to popular products like VSCode and other no-code tools would make it easier for new users to adapt to our solution.

I'll try to stress the parts I like the most and suggest a few things:

- Regarding moving the bottom panel to the left makes perfect sense. Having all the data visible on the left similar to VSCode I think is a great idea. and I think having multiple tabs, where one is visible at any time would be the best.
- Adding a dropdown for pages would simplify navigation; should we have that for apps too? something like my-app `⌄` - main-page `⌄`

A few other ideas:

- Making the distinction between components on the right panel (can include all atoms) and the components on the left created by the user. Maybe call the ones on the left panel Custom Components.
- Simplifying the create new element process: instead of using create element modal, we can mainly rely on drag-drop components from the right panel; or drag-drop custom components from the left components tab.
- A minor one, but shall we have a dark theme?
