### ISSUE TITLE
Redirect/Refresh when auth token is expired 

### ISSUE THREAD

**Issue by assimhabeek** [codelab-app/platform#2149]
## What Feature Can Be Enhanced?
When auth token is expired we should refresh it or redirect user to landing page.
  
![image](https://user-images.githubusercontent.com/33001357/211275024-10438568-bc7c-47d0-8607-da4742c1f446.png)

**Comment by melhamin** [comment]
The easiest solution would be to just redirect to login when the `accessToken` is expired. But the problem is that when redirected from `/api/graphql` to `/api/auth/login` we get a CORS error. 

<img width="1728" alt="Screenshot 2023-05-01 at 13 47 40" src="https://user-images.githubusercontent.com/48331678/235442494-2e063b29-8428-40ee-8fc0-f7d08e3b63d1.png">

This is normal. Because the browsers don't allow the same origin requests unless the server is configured to allow a web origin. So to fix this we need to add `http://127.0.0.1:3000` to the `Allowed Origins CORS` and `Allowed Web Origins` on Auth0 dashboard. But even after setting allowed web origins on Auth0 client application, the error persists. 

I have tried adding the origin without the port `http://127.0.0.1` as well but still no luck.

Another option is to use [refresh token](https://auth0.com/docs/secure/tokens/refresh-tokens). So when the `accessToken` is expired, the server would use the refresh token to automatically issue a new one.

**Comment by webberwang** [comment]
After some debugging, issue is we need to modify the Auth0 withPageAuthRequired version and redirect there, we can do that by checking the expiry date on session data
