### ISSUE TITLE
Allow capital letters for app/page/elements/etc names

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2233]
## Current Behavior
<img width="365" alt="Screenshot 2023-02-05 at 13 41 13" src="https://user-images.githubusercontent.com/74900868/216819223-91e8c971-e1a5-4879-b18a-a36bec585a37.png">
<img width="547" alt="Screenshot 2023-02-05 at 13 41 38" src="https://user-images.githubusercontent.com/74900868/216819247-baf3e831-9c75-4f6c-a36d-6c431f8dffaa.png">
<img width="570" alt="Screenshot 2023-02-05 at 13 42 06" src="https://user-images.githubusercontent.com/74900868/216819263-20152db1-ec7b-4435-b317-d813e86f9ed1.png">

**Comment by mohasarc** [comment]
There don't seem to be an easy way to allow this behaviour because [`@unique`](https://neo4j.com/docs/graphql-manual/current/type-definitions/indexes-and-constraints/#_unique_directive_usage) constraint we use for app, page, and element names is case-insensitive.

**Comment by mohasarc** [comment]
We have explored using [graphql-middleware](https://stackoverflow.com/questions/70649855/graphql-custom-directive-enforcing-value-restrictions) and [custom-directives](https://neo4j.com/docs/graphql-manual/current/type-definitions/custom-directives/). However, we diceded to go with ristricting the names to be in the Title Case.

The reason for the desicion is that graphql-middleware doesn't scale well because we'd need to write a middleware for create/update for each model. On the other hand, the custom directive would need to access the DB and that turned out to be rather complicated to implement.
