### ISSUE TITLE
Impossible to use AntDesignLink atom

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2238]
## Current Behavior
Multiple errors are thrown when Link is created. As a result - it does not render at all.

## Video Showing Bug

https://user-images.githubusercontent.com/74900868/216842935-122e1409-890f-4e60-bdfb-a882479b48cb.mov

Relates:
- #1871

**Comment by ky213** [comment]
after investigation, it turned out that the "Anchor.Link"  should always be nested in an Anchor atom, as per AntDEsign documentation.
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/22745510/217937694-0917f0f3-024f-4368-9cbc-2ff7f39ca093.png">
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/22745510/217937789-02d0cbb2-436b-443d-8a31-5ba08f4da3e9.png">

**Comment by ky213** [comment]
@webberwang @vladyslav-polishchuk 
so, what behavior do you prefer: to show an alert telling that "AnchorLink" should be nested within an "Anchor" parent, 
or automatically checking and setting the parent Anchor atom?

**Comment by webberwang** [comment]
you’re looking at antd 5 docs perhaps, we are still on 4 right

**Comment by ky213** [comment]
no, I did select the right version

**Comment by ky213** [comment]
besides, I reproduced the problem in a separate environment. It threw the same error.

**Comment by vladyslav-polishchuk** [comment]
In this case, I think there is no need to implement a special fix for the Anchor. But maybe we can investigate the scope of work and think about the solution to how to handle this problem in general. There are several atoms that can only be nested in a specific parent:
Anchor -> AnchorLink
BreadCrumb -> BreadCrumbItem -> BreadCrumbSeparator
Card -> CardGrid -> CardMeta
Dropdown -> DropdownButton
etc.
If such components are rendered in an invalid parent - either noting renders or script error is thrown.
Ideally - DnD and Atom creation dialog should validate the target parent element and filter out invalid options.
@webberwang , @ky213

**Comment by ky213** [comment]
I prefer throwing an error message at the user, what do you think guys?
@webberwang @vladyslav-polishchuk

**Comment by webberwang** [comment]
@vladyslav-polishchuk @ky213 let's move discussion to linked #1871, it is a more general case of this current issue

**Comment by melhamin** [comment]
@webberwang as suggested [here](https://github.com/codelab-app/platform/issues/1871#issuecomment-1428703090), I also believe we could replace `allowedChildren` with `allowedParent` field to handle this issue. However, I suggest having both fields. `allowedChildren` could be used when adding a child from the `ExplorerPane`, and `allowedParent` could be used when using `dnd`. We could handle both use cases with only `allowedParent` field with a bit of extra logic added.

Any other ideas?

**Comment by melhamin** [comment]
@webberwang as suggested [here](https://github.com/codelab-app/platform/issues/1871#issuecomment-1428703090), I also believe we need an extra `allowedParent` field for atoms, not instead of `allowedChildren` field though. Only `allowedParent` field wouldn't handle the use cases of the `allowedChildren`. The `allowedParent` would be specific to some elements mentioned above.

Any other ideas?

**Comment by melhamin** [comment]
Fixed #2321
