### ISSUE TITLE
Type table search does not work

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#2276]
## Description

Currently the Ant Design table searches using data from the frontend, but with pagination we don't have all the data on the front.

We'll need to call backend API with `limit` and `offset` to get the current types

---

A dev mentioned that search was working before this PR, 

- https://github.com/codelab-app/platform/pull/2148

You can use that as reference

---

https://user-images.githubusercontent.com/26264925/219482956-7eec37d4-900b-4d4d-a1eb-678539f34fef.mov

**Comment by mohasarc** [comment]
After some investigation #2148 doesn't seem to affect this. The issue seems to have been be introduced after #2132 because there we'd stopped using the `where` property.

Some context: `useTypesTable` exports `baseTypeWhere` whose value changes when the search keyword change. On the other hand, `getBaseTypes` exported from `useTypesTableData` accepts a `where` property.

So basically we need to call `getBaseTypes` with `baseTypeWhere` whenever it changes to fetch the types from the backend.
