### ISSUE TITLE
Parent should show name instead of ID

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#2308]
## Description

https://github.com/codelab-app/platform/issues/2261#issuecomment-1441290920

- [x] Add parent node name in parenthesis to element selection option
 
![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/26264925/221628671-bd5d1e42-4702-4735-8f30-00f463a6842f.jpg)

- [x] Add a `+` button for each elementTree scope. 1 for page and 1 for each component

**Comment by mohasarc** [comment]
It turned out that the core cause of this issue is that we calculate lebels by finding the element names in the element tree, but we're passing only the page's element tree and ignoring the components trees.

If we pass the component trees too and allow showing the names of all elements, user experience might suffer because there is no name uniqueness constraint between components' elements and the page's elements. This means the list could potentially contain multiple elements with the same name.

Potential solutions to remove the confusion when setting the parent element:
1. Append "Page" or the name of the component in parantheses to the element names showed in ParentElement field.
3. Add a `+` button for each component separatly, kind of similar to the suggestion from #2256.

I'm more gravitated towards 1 as it is a little simpler to implement.

**Comment by webberwang** [comment]
Could you create a builder demo and screenshot then label the areas you are referring to?

**Comment by Brilliantwebdev1125** [comment]
NO. sorry.

**Comment by mohasarc** [comment]
1. The elements visible in Parent Element list are only the onse from the active element tree. In this ss it is the page tree

![Screenshot from 2023-02-27 10-51-33](https://user-images.githubusercontent.com/51242349/221509326-c0a35a21-d67e-4de4-845e-89e576efc6ca.png)

2. If we're gonna show all elements some will end up having the same name

![Screenshot from 2023-02-27 11-17-49](https://user-images.githubusercontent.com/51242349/221510229-a8ddd64d-8c70-4ea0-bd74-bf63f99487a0.png)

so we can add in parentheses where each element is coming from

![Screenshot from 2023-02-27 10-51-33-2](https://user-images.githubusercontent.com/51242349/221509537-8a603428-abf9-4ed5-a60d-cd98f1cc0cbb.jpg)

3.       

![Screenshot from 2023-02-27 11-04-34](https://user-images.githubusercontent.com/51242349/221510532-cdf5f1be-9336-4630-a003-464f51e9adbf.jpg)
