### ISSUE TITLE
Component root element name is invalid

### ISSUE THREAD

**Issue by melhamin** [codelab-app/platform#2527]
## Current Behavior
The atom for the root element of acomponent cannot be set. It gets reset right after selecting an atom.

## Video Showing Bug

https://user-images.githubusercontent.com/48331678/233830475-2ab017a9-1450-4f93-8994-76455711c27c.mov

**Comment by vladyslav-polishchuk** [comment]
This is because `HtmlLink` is not a valid name for an element, making the form invalid and preventing submission to the server.
Though this name is automatically assigned when a component is created. Should we maybe also set the same name validation pattern for the component name as we do for elements to avoid this behavior?
Or alternatively, transform the root element name to a valid one once the component is created

**Comment by melhamin** [comment]
I guess the easiest solution would be to use the same validation pattern for component names as well. @webberwang ?

**Comment by webberwang** [comment]
> This is because `HtmlLink` is not a valid name for an element, making the form invalid and preventing submission to the server. Though this name is automatically assigned when a component is created. Should we maybe also set the same name validation pattern for the component name as we do for elements to avoid this behavior? Or alternatively, transform the root element name to a valid one once the component is created

Yeah let's try that out
