### ISSUE TITLE
Filter not used metadata for production websites

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2597]
## What Feature Can Be Enhanced?
Currently, production user websites load information about the app/page and ALL metadata: interfaces, fields, atoms,etc without checking if this information is required for specific page.
This approach has two negative effects on production websites performance:
- big page size, even for simple pages. next.js also shows warning about this in console:
`Warning: data for page "/[domain]/[...page]" (path "/codelab-demo.online/page") is 341 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.`
This leads to delay of displaying page to the user since need to download large file with data first.
- all these interfaces are very expensive to load into the store. Lighthouse shows low performance score for a very simple page with single text element, and the interfaces and fields take 2 seconds of blocking time to just be loaded.
<img width="1728" alt="Screenshot 2023-05-05 at 18 29 50" src="https://user-images.githubusercontent.com/74900868/236515049-4fab005b-686c-4b84-b0de-cc8bb38f9df2.png">

**Comment by webberwang** [comment]
Maybe interfaces isn't need for runtime just build time, similar to how typescript works.

**Comment by vladyslav-polishchuk** [comment]
> @vladyslav-polishchuk how to reproduce this?

Discussed in DM

**Comment by vladyslav-polishchuk** [comment]
> Maybe interfaces isn't need for runtime just build time, similar to how typescript works.

If this is possible - this may be a significant performance improvement for user pages

**Comment by nettohadi** [comment]
# How to Run the Websites Locally

### Assign a Domain to Your App
If you haven't already, start by creating an app. Then, follow the steps below to assign a domain to it. In this example, we'll use "codelab.id" as our domain:

1. Find your app's card and click on the three-dot menu icon located at its top-right corner.
2. From the dropdown list, select "Domains."
3. In the top-right corner of the Domains section, click on the "+" icon to add a new domain.
4. Enter your desired domain name in the "Name" field. Ensure it is URL-friendly.
5. Hit the "Create Domain" button.
6. If you encounter an error message stating "Domain misconfigured because it's already assigned to another project," you can safely ignore it.

### Pointing the Newly-Created Domain to Your Local IP Address
After setting up your domain, the subsequent step involves directing it towards your local IP address. This mirrors the DNS resolution process on our production server. Instructions vary based on the operating system in use. Below are the detailed steps for Mac, Windows, and Linux:

#### Mac:
1. **Open the Terminal**: You can do this by navigating to Applications > Utilities > Terminal.
2. **Edit the hosts file**: In the terminal, type `sudo nano /etc/hosts` and press Enter. This will open the hosts file in the nano text editor.
3. **Add your domain**: At the end of the file, append your local IP address, followed by the domain name:
   ```
   127.0.0.1    yourdomain.com
   ```
   Then press `Control + O` to save and `Control + X` to exit.
4. **Flush the DNS cache**: To ensure your changes take immediate effect, type:
   ```
   sudo killall -HUP mDNSResponder
   ```
   and press Enter.

#### Windows:
1. **Open Notepad as Administrator**: Press `Windows + S`, type "Notepad", right-click the result, and select "Run as administrator".
2. **Edit the hosts file**: In Notepad, go to File > Open, navigate to `C:\Windows\System32\drivers\etc`, change "Text Documents (*.txt)" to "All Files", and open the `hosts` file.
3. **Enter your domain**: At the end, add your local IP address followed by your domain:
   ```
   127.0.0.1    yourdomain.com
   ```
   Save and close the file.
4. **Flush the DNS cache**: Open a command prompt as administrator and type:
   ```
   ipconfig /flushdns
   ```
   Then press Enter.

#### Linux:
1. **Open the Terminal**: This can usually be accessed from the Applications menu or by pressing `Ctrl + Alt + T`.
2. **Modify the hosts file**: Type `sudo nano /etc/hosts` and press Enter.
3. **Specify your domain**: Append your local IP address followed by your domain name at the file's end:
   ```
   127.0.0.1    yourdomain.com
   ```
   Press `Control + O` to save and `Control + X` to exit.
4. **Refresh the DNS cache**: Depending on the Linux distribution, the method to flush the DNS cache might differ. For systems using `systemd-resolved`, you can type:
   ```
   sudo systemd-resolve --flush-caches
   ```
   and press Enter.

Now, with these steps completed for your respective OS, the domain should direct to your local IP address.


### Create a Custom  Page
Ensure you have pages aside from system pages like 500, 400, and app. If you don't, here's how to create one. As an example, we'll set up a home page:
1. Navigate to the "Pages" tab and select the "+" icon to add a new page.
2. Enter "Home" for the Name and set the Deployed Page URL as "/home".
3. Click on "Create Page".

### Set Up Port 80 for the Websites
1. Navigate to the `websites` folder and open the `project.json` file.
2. Locate the port setting, which is currently set to `3000`.
3. Since port `3000` is already occupied by the platform, we need to switch to another port. We'll use port `80` to allow domain access without needing to specify a port.
4. In the `project.json` file, navigate to: `targets > serve > options > port`.
5. Change the port value to `80` and save the file.

### Launching the Websites Locally
With the port set up, you can now run the websites on your local machine. Ensure the `platform-api`, `platform`, and `websites` are all running concurrently. Then, simply input `http://codelab.id/home` into your browser. This will load the website associated with the "codelab.id" domain, specifically directing you to the "/home" page.
