### ISSUE TITLE
Impossible to select component props form

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2717]
## What Feature Can Be Enhanced?
When any component is opened by edit button:
<img width="339" alt="Screenshot 2023-06-14 at 22 24 24" src="https://github.com/codelab-app/platform/assets/74900868/d811377b-2131-4642-9e02-51c090f4492b">
then the component props form is shown where it is possible to edit component api:
<img width="1690" alt="Screenshot 2023-06-14 at 22 25 42" src="https://github.com/codelab-app/platform/assets/74900868/26c03da3-a8fc-4381-b28b-9f70bb4bc9c7">
But once any of the component children is selected in explorer tree - it becomes impossible to components props form again:

https://github.com/codelab-app/platform/assets/74900868/b8964f60-b15d-43c0-b277-614581c55859

As a solution can be implemented:
1. allow user to deselect element from explorer tree by focus out or shift+click
2. add root element to explorer tree which will represent component, and when it is selected - display props form for component (and other forms that are available on the right panel)
3. TBD

**Comment by webberwang** [comment]
I think 2 makes sense, you mean adding a Component node in the explorer tree?

**Comment by vladyslav-polishchuk** [comment]
> I think 2 makes sense, you mean adding a Component node in the explorer tree?

Yes, exactly

**Comment by webberwang** [comment]
@mohasarc any thoughts? since you work on the UI

**Comment by mohasarc** [comment]
The issue actually stems from having multiple views that replace each other in the components sidebar: one for the custom components and the other for the element tree with a back arrow to go back to custom components. This prevents qucik switch between the custom components view and the element tree view.

Instead of that we need to redirect to Explorer sidebar panel (which has the element view) when clicking the edit button on the component. In which case the switch between the sidebars is seemless using the side navigation bar.

![Group 157](https://github.com/codelab-app/platform/assets/51242349/940b9fe5-808b-4801-9b5c-07f77d5685f5)


![Group 158](https://github.com/codelab-app/platform/assets/51242349/20bb3b3e-2240-46a0-871c-7dfa3a37c351)


This is in fact analogous to how we navigate between pages and their explorers

![Group 159](https://github.com/codelab-app/platform/assets/51242349/21534e86-d436-42c3-91d0-42d93fabf62f)


![Group 160](https://github.com/codelab-app/platform/assets/51242349/9be16de1-3e5e-46fb-8714-095fb2dcb809)


In principle I think we should not allow sidebars to have multiple views that replace each other.

**Comment by webberwang** [comment]
@mohasarc so you're basically saying the right panel view should be synced to the sidebar?

**Comment by mohasarc** [comment]
Not directly. it is influenced by what is selected in the primary sidebar. We can add an optional feature though: if an item is previosly selected in components view for example, navigating to the components primary sidebar would be sufficient to trigger the secondary sidebar.

**Comment by mohasarc** [comment]
So in essence:

Navigation bar - influences -> Primary Sidebar - influences -> Edito View and Secondary sidbar
