### ISSUE TITLE
Add hooks on element

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#2738]
## Description
Looks like we have `preRenderAction` and `postRenderAction` for the element model but there is no logic or implementation yet to actually make it work.

We will need this for something like where the element needs to fetch an array of data from an API upon rendering the element to be able to display those data.

**Comment by vladyslav-polishchuk** [comment]
@jethrocabaluna , @webberwang 
I understand what is `preRenderAction` and how we can benefit from having it (this is probably `useEffect` without dependency array). But what is `postRenderAction`?
Also, for the use case described in the issue, `preRenderAction` will not be a good place to do API calls, since it will be invoked too often. Maybe we need to have `onMountAction` (which is `useEffect(..., [])`) and `onUnmountAction`?

**Comment by assimhabeek** [comment]
@vladyslav-polishchuk the idea was two hooks one runs before starting element render, and the other after element rendering is done.

**Comment by vladyslav-polishchuk** [comment]
@assimhabeek , any ideas on the use case when we may need `postRenderAction`? So that I can better understand how to implement it so we can maximize the benefit

**Comment by assimhabeek** [comment]
I imagine `postRenderAction` to be the one that uses `onMountEvent` api calls will probably go here.  

As for `preRenderAction` it will be called by `renderElement` before starting the render.  When working with `auth` I remember having to read from local storage and updating the state before rendering the element.
