### ISSUE TITLE
Deploy to production with data

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#3060]
## Description

We want to go back to our production flow, and start syncing data to our remote server. We will add an admin button that syncs to production, this will take the json data and sync there.

We won't use seeder anymore, but rather add each atom/interface by hand. (this part you can do a couple just to show that it can work)

**Comment by webberwang** [comment]
@vladyslav-polishchuk 
- Another thought, say we want to start adding the api to our Ant Design atoms, we would only do that locally right. Since to export we would download directly to codebase.
- Let's take a look at https://ant.design/components/button and add all the missing api. This will let us know what types we can't support yet. At least this way we know what to prioritize

**Comment by vladyslav-polishchuk** [comment]
@webberwang,

- with latest changes import can be executed more than once without errors (both locally and locally with production env). After export - data without changes is exported, except `owner` id property, it depends on who made the import (maybe we can exclude `owner` from all seed files since it is anyway overwritten with current user?). Also it is possible to edit seed data (add/remove some API field, edit some atom, etc.) and execute import one more time and the changes will update the DB.
Should I proceed with individual atoms import as described in issue description?
- as of missing api for AntDesignButton atom, I see there were recently introduced for many of the antd components
  - `classNames` of type `Record<SemanticDOM, string>`;
  - `styles` of type `Record<SemanticDOM, CSSProperties>`;
  This props allow to set custom class names and styles for nested elements. For example, for button it is possible to set class names and styles for `icon` that may exist inside the button. 
  But it is an interesting question if we need to incorporate these properties into apis of our atoms. Adding them as simple fields on atom props form may not make much sense, since it will not support breakpoints there, as in our `CSS` tab. To make this property contain different values for different breakpoints would be not an easy task. Probably we can stick with our `CSS` tab which already allows to specify selector for nested elements and supports breakpoints, and skip `classNames` and `styles` at all, what do you think?
<img width="1353" alt="Screenshot 2023-11-11 at 10 17 21" src="https://github.com/codelab-app/platform/assets/74900868/04e7171b-02b1-4a95-bee9-1bd436cfad22">
- also there is mismatch in types for `loading` property (I also see this similar issue in other atoms as well), it is currently enum which shows the data types isntead of being UnionType and allow to specify value of any of thouse data types:
<img width="328" alt="Screenshot 2023-11-11 at 10 21 41" src="https://github.com/codelab-app/platform/assets/74900868/a17134a9-7777-4d6f-99db-fa0f4d2423d9">

This needs to be changed to UnionType, to allow user to set either `true` or `false`, or specify an integer `delay` property.
But currently there is some problem with defining UnionTypes, even simple union can't be created:
<img width="1309" alt="Screenshot 2023-11-11 at 10 24 24" src="https://github.com/codelab-app/platform/assets/74900868/d3fcd26f-b3c4-476b-9828-52f314d18a31">
Will have a look into this and then try to replace Enum with Union for `loading` button prop.
- regarding action types, you mentioned that they may be more difficult. Could you expand what do you mean? I see currently action type seem to work, I can attach either store action or expression with function for `onClick` and it is getting called properly

**Comment by webberwang** [comment]
@vladyslav-polishchuk 
- why would it depend on who made the import? I think all user should be omitted
- the SemanticDOM design by ant design is a bit odd https://github.com/ant-design/ant-design/discussions/40221, not sure if we really need it
- @melhamin are you able to add a spec for union type and fix the issue? https://github.com/codelab-app/platform/issues/3103

**Comment by vladyslav-polishchuk** [comment]
> @vladyslav-polishchuk
> 
> * why would it depend on who made the import? I think all user should be omitted
> * the SemanticDOM design by ant design is a bit odd [[RFC] Semantic DOM Structure for all Components ant-design/ant-design#40221](https://github.com/ant-design/ant-design/discussions/40221), not sure if we really need it
> * @melhamin are you able to add a spec for union type and fix the issue? [Cover more cases in type transformer specs #3103](https://github.com/codelab-app/platform/issues/3103)

@webberwang 
- `owner` gets overwritten with the user from the request. So if I would seed the production DB - my user id would be used as owner for entities, if someone else would import - that user ID would be used as owner.
Here is how `owner` is getting overwritten for atoms, for example (`libs/backend/domain/atom/src/repository/atom.repo.service.ts`):
<img width="702" alt="Screenshot 2023-11-11 at 21 27 14" src="https://github.com/codelab-app/platform/assets/74900868/0144ed10-b163-42c4-ba8b-996cf3295fb5">

- I also think we can skip it at the moment and provide a single consistent way to alter styling through `CSS` tab
- I already had a look at why UnionType can't be created, seems like need to uncomment recent changes in schema (and do `yarn codegen`):
<img width="1102" alt="Screenshot 2023-11-11 at 21 23 06" src="https://github.com/codelab-app/platform/assets/74900868/e5bee0ee-c6ec-46b9-8afb-a147a36e0c39">
Don't know why the lines were commented, though. @melhamin if you would work on the issue - hope this info will help

**Comment by webberwang** [comment]
@vladyslav-polishchuk 
- For seeding production, we can all share the same user account so the overwritten user won't be an issue

**Comment by vladyslav-polishchuk** [comment]
@webberwang 
One more question, how do we plan to handle inconsistencies between antd APIs and the seed data (`data/export-v3`). I see some mismatches currently. Do we plan to rework the scraper script so that it exports data in the new format and run it from time to time, or from now on we would keep track of the changes in antd APIs and sync them manually?

**Comment by webberwang** [comment]
@vladyslav-polishchuk 

The seeder actually should be deprecated (reading from scraped data), all updates will be done via the UI to change the API, then export to replace the json data.

Transforming scraped data is only good for 50-60% of the types which we already have. The rest can be manually done as it's only a 1 time thing
