### ISSUE TITLE
Prop inspector updates do not re-render

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#3252]
## Description

1. Create button
2. Modify `customText` in prop inspector
3. Reload page to see update

**Comment by melhamin** [comment]
@webberwang The problem here is only the `customText` prop, others work fine. Does it make sense to allow editing `customText` in the props inspector at all?

The format of the editor content is not very user-friendly to allow custom editing.

<img width="1724" alt="Screenshot 2024-03-09 at 11 52 09 PM" src="https://github.com/codelab-app/platform/assets/48331678/e2adc35e-f6d7-497e-883a-461915a480c0">
